name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo_mysql, bcmath, ctype, json, tokenizer, xml

    - name: Copy .env
      run: cp .env.example .env
      
    - name: Install Dependencies
      run: composer install --no-interaction

    - name: Generate key
      run: php artisan key:generate

    - name: Compile JS & CSS
      run: npm install && npm run build